version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # By this config we can access to host whitin container via host.docker.internal address.
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis:alpine3.18
    restart: unless-stopped
    volumes:
      - redis-data:/data

    # Add "forwardPorts": ["6379"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  redis-data: